using System.IO.Hashing;
using System.Text;

namespace DummyFileApi.Generators;

/// <summary>
/// A .docx is an OOXML package — a ZIP of XML parts. All parts here are fixed
/// except one filler paragraph in <c>word/document.xml</c>, so the archive size
/// solves in one step for that paragraph's text length, with no padding container.
/// Past <see cref="MaxFillerTextLength"/> the text stops growing and an embedded
/// PNG takes the remaining bytes instead, again in one step.
/// </summary>
public sealed class DocxFileGenerator : IFileGenerator
{
    // Word caps a document's text at 32 MB and slows badly on huge paragraphs,
    // so filler text stops growing here; bigger targets embed an image.
    private const long MaxFillerTextLength = 1024 * 1024;

    // 6 inches square (914,400 EMU per inch) — fits inside the page margins.
    private const string ImageExtentEmu = "5486400";

    private const string Prolog = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\r\n";

    private const string ContentTypesXml = Prolog +
        "<Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\">" +
        "<Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/>" +
        "<Default Extension=\"xml\" ContentType=\"application/xml\"/>" +
        "<Override PartName=\"/word/document.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml\"/>" +
        "<Override PartName=\"/docProps/core.xml\" ContentType=\"application/vnd.openxmlformats-package.core-properties+xml\"/>" +
        "<Override PartName=\"/docProps/app.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.extended-properties+xml\"/>" +
        "</Types>";

    private const string ImageContentTypesXml = Prolog +
        "<Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\">" +
        "<Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/>" +
        "<Default Extension=\"xml\" ContentType=\"application/xml\"/>" +
        "<Default Extension=\"png\" ContentType=\"image/png\"/>" +
        "<Override PartName=\"/word/document.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml\"/>" +
        "<Override PartName=\"/docProps/core.xml\" ContentType=\"application/vnd.openxmlformats-package.core-properties+xml\"/>" +
        "<Override PartName=\"/docProps/app.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.extended-properties+xml\"/>" +
        "</Types>";

    private const string PackageRelsXml = Prolog +
        "<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">" +
        "<Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"word/document.xml\"/>" +
        "<Relationship Id=\"rId2\" Type=\"http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties\" Target=\"docProps/core.xml\"/>" +
        "<Relationship Id=\"rId3\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties\" Target=\"docProps/app.xml\"/>" +
        "</Relationships>";

    // The text-only document references nothing external, so its relationship part is empty.
    private const string DocumentRelsXml = Prolog +
        "<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"/>";

    private const string ImageDocumentRelsXml = Prolog +
        "<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">" +
        "<Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/image\" Target=\"media/image1.png\"/>" +
        "</Relationships>";

    private const string CorePropsXml = Prolog +
        "<cp:coreProperties xmlns:cp=\"http://schemas.openxmlformats.org/package/2006/metadata/core-properties\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\">" +
        "<dc:title>Dummy Document</dc:title><dc:creator>dummy-file-api</dc:creator>" +
        "</cp:coreProperties>";

    private const string AppPropsXml = Prolog +
        "<Properties xmlns=\"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties\">" +
        "<Application>dummy-file-api</Application>" +
        "</Properties>";

    private const string TitleParagraph =
        "<w:p><w:r><w:t>Dummy document generated by dummy-file-api.</w:t></w:r></w:p>";

    private const string FillerParagraphOpen = "<w:p><w:r><w:t xml:space=\"preserve\">";

    // word/document.xml = a prefix + the filler paragraph's text + this suffix.
    private const string DocumentPrefix = Prolog +
        "<w:document xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\"><w:body>" +
        TitleParagraph + FillerParagraphOpen;

    private const string ImageDocumentPrefix = Prolog +
        "<w:document xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\"" +
        " xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"" +
        " xmlns:wp=\"http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing\"" +
        " xmlns:a=\"http://schemas.openxmlformats.org/drawingml/2006/main\"" +
        " xmlns:pic=\"http://schemas.openxmlformats.org/drawingml/2006/picture\"><w:body>" +
        TitleParagraph +
        "<w:p><w:r><w:drawing><wp:inline distT=\"0\" distB=\"0\" distL=\"0\" distR=\"0\">" +
        "<wp:extent cx=\"" + ImageExtentEmu + "\" cy=\"" + ImageExtentEmu + "\"/>" +
        "<wp:effectExtent l=\"0\" t=\"0\" r=\"0\" b=\"0\"/>" +
        "<wp:docPr id=\"1\" name=\"Picture 1\"/>" +
        "<wp:cNvGraphicFramePr><a:graphicFrameLocks noChangeAspect=\"1\"/></wp:cNvGraphicFramePr>" +
        "<a:graphic><a:graphicData uri=\"http://schemas.openxmlformats.org/drawingml/2006/picture\"><pic:pic>" +
        "<pic:nvPicPr><pic:cNvPr id=\"0\" name=\"image1.png\"/><pic:cNvPicPr/></pic:nvPicPr>" +
        "<pic:blipFill><a:blip r:embed=\"rId1\"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill>" +
        "<pic:spPr><a:xfrm><a:off x=\"0\" y=\"0\"/><a:ext cx=\"" + ImageExtentEmu + "\" cy=\"" + ImageExtentEmu + "\"/></a:xfrm>" +
        "<a:prstGeom prst=\"rect\"><a:avLst/></a:prstGeom></pic:spPr>" +
        "</pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r></w:p>" +
        FillerParagraphOpen;

    private const string DocumentSuffix =
        "</w:t></w:r></w:p>" +
        "<w:sectPr><w:pgSz w:w=\"12240\" w:h=\"15840\"/>" +
        "<w:pgMar w:top=\"1440\" w:right=\"1440\" w:bottom=\"1440\" w:left=\"1440\" w:header=\"720\" w:footer=\"720\" w:gutter=\"0\"/>" +
        "</w:sectPr></w:body></w:document>";

    private const string DocumentPartName = "word/document.xml";
    private const string ImagePartName = "word/media/image1.png";

    // Declared before the layouts: their Overhead reads it during static init.
    private static readonly byte[] DocumentSuffixBytes = Encoding.ASCII.GetBytes(DocumentSuffix);

    private static readonly PackageLayout TextLayout = new(
        [
            ("[Content_Types].xml", Encoding.ASCII.GetBytes(ContentTypesXml)),
            ("_rels/.rels", Encoding.ASCII.GetBytes(PackageRelsXml)),
            ("word/_rels/document.xml.rels", Encoding.ASCII.GetBytes(DocumentRelsXml)),
            ("docProps/core.xml", Encoding.ASCII.GetBytes(CorePropsXml)),
            ("docProps/app.xml", Encoding.ASCII.GetBytes(AppPropsXml)),
        ],
        Encoding.ASCII.GetBytes(DocumentPrefix),
        HasImage: false);

    private static readonly PackageLayout ImageLayout = new(
        [
            ("[Content_Types].xml", Encoding.ASCII.GetBytes(ImageContentTypesXml)),
            ("_rels/.rels", Encoding.ASCII.GetBytes(PackageRelsXml)),
            ("word/_rels/document.xml.rels", Encoding.ASCII.GetBytes(ImageDocumentRelsXml)),
            ("docProps/core.xml", Encoding.ASCII.GetBytes(CorePropsXml)),
            ("docProps/app.xml", Encoding.ASCII.GetBytes(AppPropsXml)),
        ],
        Encoding.ASCII.GetBytes(ImageDocumentPrefix),
        HasImage: true);

    private static readonly PngFileGenerator Png = new();

    // Held just under the cap so the smallest image-bearing target still leaves
    // room for the smallest valid PNG.
    private static readonly long ImageFillerTextLength =
        MaxFillerTextLength - (ImageLayout.Overhead - TextLayout.Overhead) - Png.MinSizeBytes;

    public string TypeKey => "docx";
    public string MimeType => "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
    public string FileExtension => "docx";

    public long MinSizeBytes => TextLayout.Overhead;

    public async Task GenerateAsync(Stream output, long targetSizeBytes, int? seed, CancellationToken cancellationToken = default)
    {
        if (targetSizeBytes < MinSizeBytes)
        {
            throw new ArgumentOutOfRangeException(nameof(targetSizeBytes));
        }

        var textOnlyFillerLength = targetSizeBytes - TextLayout.Overhead;
        var layout = textOnlyFillerLength <= MaxFillerTextLength ? TextLayout : ImageLayout;
        var fillerLength = layout.HasImage ? ImageFillerTextLength : textOnlyFillerLength;
        var imageLength = targetSizeBytes - layout.Overhead - fillerLength;

        // seed picks the filler phrase (and the image's color) — like png's
        // palette, it changes the bytes but not the size, which the target fixes regardless.
        var phrase = FillerPhrases.AllBytes[SeedIndex.Wrap(seed, FillerPhrases.AllBytes.Length)];
        var prefix = layout.DocumentPrefix;
        var crc = ZipWriter.FramedRepeatingCrc32(prefix, phrase, fillerLength, DocumentSuffixBytes);

        var writer = new ZipWriter(output);
        foreach (var (name, content) in layout.FixedParts)
        {
            await writer.AddEntryAsync(name, content, cancellationToken);
        }

        await writer.AddEntryAsync(
            DocumentPartName,
            prefix.Length + fillerLength + DocumentSuffixBytes.Length,
            crc,
            (stream, ct) => ZipWriter.WriteFramedRepeatingAsync(stream, prefix, phrase, fillerLength, DocumentSuffixBytes, ct),
            cancellationToken);

        if (layout.HasImage)
        {
            // The PNG is deterministic, so it's generated once to hash for the
            // local header and again to stream it — never buffered.
            var imageCrc = new Crc32Sink();
            await Png.GenerateAsync(imageCrc, imageLength, seed, cancellationToken);

            await writer.AddEntryAsync(
                ImagePartName,
                imageLength,
                imageCrc.Hash,
                (stream, ct) => Png.GenerateAsync(stream, imageLength, seed, ct),
                cancellationToken);
        }

        await writer.FinishAsync(cancellationToken);
    }

    // Every byte except the filler text (and the image, when present) is fixed,
    // so Overhead is the whole archive when both are empty.
    private sealed record PackageLayout((string Name, byte[] Content)[] FixedParts, byte[] DocumentPrefix, bool HasImage)
    {
        public long Overhead { get; } = ComputeOverhead(FixedParts, DocumentPrefix, HasImage);

        private static long ComputeOverhead((string Name, byte[] Content)[] fixedParts, byte[] documentPrefix, bool hasImage)
        {
            string[] partNames = hasImage
                ? [.. fixedParts.Select(p => p.Name), DocumentPartName, ImagePartName]
                : [.. fixedParts.Select(p => p.Name), DocumentPartName];

            return ZipWriter.OverheadFor(partNames)
                + fixedParts.Sum(p => (long)p.Content.Length)
                + documentPrefix.Length
                + DocumentSuffixBytes.Length;
        }
    }

    // Write-only sink that just hashes what the PNG generator writes.
    private sealed class Crc32Sink : Stream
    {
        private readonly Crc32 _crc = new();

        public uint Hash => _crc.GetCurrentHashAsUInt32();

        public override bool CanRead => false;
        public override bool CanSeek => false;
        public override bool CanWrite => true;
        public override long Length => throw new NotSupportedException();

        public override long Position
        {
            get => throw new NotSupportedException();
            set => throw new NotSupportedException();
        }

        public override void Flush()
        {
        }

        public override int Read(byte[] buffer, int offset, int count) => throw new NotSupportedException();

        public override long Seek(long offset, SeekOrigin origin) => throw new NotSupportedException();

        public override void SetLength(long value) => throw new NotSupportedException();

        public override void Write(byte[] buffer, int offset, int count) => _crc.Append(buffer.AsSpan(offset, count));

        public override void Write(ReadOnlySpan<byte> buffer) => _crc.Append(buffer);

        public override ValueTask WriteAsync(ReadOnlyMemory<byte> buffer, CancellationToken cancellationToken = default)
        {
            _crc.Append(buffer.Span);
            return ValueTask.CompletedTask;
        }

        public override Task WriteAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
        {
            _crc.Append(buffer.AsSpan(offset, count));
            return Task.CompletedTask;
        }
    }
}
