using System.Text;

namespace DummyFileApi.Generators;

/// <summary>
/// A .docx is an OOXML package — a ZIP of XML parts. All parts here are fixed
/// except one filler paragraph in <c>word/document.xml</c>, so the archive size
/// solves in one step for that paragraph's text length, with no padding container.
/// </summary>
public sealed class DocxFileGenerator : IFileGenerator
{
    private const string Prolog = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\r\n";

    private const string ContentTypesXml = Prolog +
        "<Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\">" +
        "<Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/>" +
        "<Default Extension=\"xml\" ContentType=\"application/xml\"/>" +
        "<Override PartName=\"/word/document.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml\"/>" +
        "<Override PartName=\"/docProps/core.xml\" ContentType=\"application/vnd.openxmlformats-package.core-properties+xml\"/>" +
        "<Override PartName=\"/docProps/app.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.extended-properties+xml\"/>" +
        "</Types>";

    private const string PackageRelsXml = Prolog +
        "<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">" +
        "<Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"word/document.xml\"/>" +
        "<Relationship Id=\"rId2\" Type=\"http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties\" Target=\"docProps/core.xml\"/>" +
        "<Relationship Id=\"rId3\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties\" Target=\"docProps/app.xml\"/>" +
        "</Relationships>";

    // The document references nothing external, so its relationship part is empty.
    private const string DocumentRelsXml = Prolog +
        "<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"/>";

    private const string CorePropsXml = Prolog +
        "<cp:coreProperties xmlns:cp=\"http://schemas.openxmlformats.org/package/2006/metadata/core-properties\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\">" +
        "<dc:title>Dummy Document</dc:title><dc:creator>dummy-file-api</dc:creator>" +
        "</cp:coreProperties>";

    private const string AppPropsXml = Prolog +
        "<Properties xmlns=\"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties\">" +
        "<Application>dummy-file-api</Application>" +
        "</Properties>";

    // word/document.xml = this prefix + the filler paragraph's text + the suffix.
    private const string DocumentPrefix = Prolog +
        "<w:document xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\"><w:body>" +
        "<w:p><w:r><w:t>Dummy document generated by dummy-file-api.</w:t></w:r></w:p>" +
        "<w:p><w:r><w:t xml:space=\"preserve\">";

    private const string DocumentSuffix =
        "</w:t></w:r></w:p>" +
        "<w:sectPr><w:pgSz w:w=\"12240\" w:h=\"15840\"/>" +
        "<w:pgMar w:top=\"1440\" w:right=\"1440\" w:bottom=\"1440\" w:left=\"1440\" w:header=\"720\" w:footer=\"720\" w:gutter=\"0\"/>" +
        "</w:sectPr></w:body></w:document>";

    private const string DocumentPartName = "word/document.xml";

    private static readonly (string Name, byte[] Content)[] FixedParts =
    [
        ("[Content_Types].xml", Encoding.ASCII.GetBytes(ContentTypesXml)),
        ("_rels/.rels", Encoding.ASCII.GetBytes(PackageRelsXml)),
        ("word/_rels/document.xml.rels", Encoding.ASCII.GetBytes(DocumentRelsXml)),
        ("docProps/core.xml", Encoding.ASCII.GetBytes(CorePropsXml)),
        ("docProps/app.xml", Encoding.ASCII.GetBytes(AppPropsXml)),
    ];

    private static readonly byte[] DocumentPrefixBytes = Encoding.ASCII.GetBytes(DocumentPrefix);
    private static readonly byte[] DocumentSuffixBytes = Encoding.ASCII.GetBytes(DocumentSuffix);

    private static readonly string[] PartNames =
        [.. FixedParts.Select(p => p.Name), DocumentPartName];

    // Everything but the filler text has a fixed length, so this is the whole
    // archive when the filler paragraph is empty.
    private static readonly long Overhead =
        ZipWriter.OverheadFor(PartNames)
        + FixedParts.Sum(p => (long)p.Content.Length)
        + DocumentPrefixBytes.Length
        + DocumentSuffixBytes.Length;

    public string TypeKey => "docx";
    public string MimeType => "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
    public string FileExtension => "docx";

    public long MinSizeBytes => Overhead;

    public async Task GenerateAsync(Stream output, long targetSizeBytes, int? seed, CancellationToken cancellationToken = default)
    {
        if (targetSizeBytes < MinSizeBytes)
        {
            throw new ArgumentOutOfRangeException(nameof(targetSizeBytes));
        }

        var fillerLength = targetSizeBytes - Overhead;
        // seed picks the filler phrase — like png's palette, it changes the
        // bytes but not the size, which the target fixes regardless.
        var phrase = FillerPhrases.AllBytes[SeedIndex.Wrap(seed, FillerPhrases.AllBytes.Length)];
        var crc = ZipWriter.FramedRepeatingCrc32(DocumentPrefixBytes, phrase, fillerLength, DocumentSuffixBytes);

        var writer = new ZipWriter(output);
        foreach (var (name, content) in FixedParts)
        {
            await writer.AddEntryAsync(name, content, cancellationToken);
        }

        await writer.AddEntryAsync(
            DocumentPartName,
            DocumentPrefixBytes.Length + fillerLength + DocumentSuffixBytes.Length,
            crc,
            (stream, ct) => ZipWriter.WriteFramedRepeatingAsync(stream, DocumentPrefixBytes, phrase, fillerLength, DocumentSuffixBytes, ct),
            cancellationToken);

        await writer.FinishAsync(cancellationToken);
    }
}
